parameters:
#    bart_site.example.class: Bart\SiteBundle\Example

services:
#    bart_site.example:
#        class: %bart_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
